version: '3'

networks:
  servicenet:
    driver: bridge

services:
  docker-base-image:
    build: docker-base-image/
    image: docker-base-image
  chaostoolkit:
    container_name: chaostoolkit
    build: chaostoolkit-base/
    networks:
    - servicenet
    tty: true
    depends_on:
      - docker-base-image

  chaoshub:
    image: chaostoolkit/chaoshub:0.1.2
    ports:
    - "8888:8080"
    networks:
    - servicenet
    tty: true
    depends_on:
      - docker-base-image

  api-gateway:
    container_name: api-gateway
    build: api-gateway/
    # need NET_ADMIN to run chaos linux experiments
    cap_add:
     - NET_ADMIN
    ports:
    - "8080:8080"
    networks:
    - servicenet
    volumes:
      - ./chaos-scripts:/var/chaosscripts
    depends_on:
      - docker-base-image

  fashion:
    container_name: bestseller-fashion
    build: api-gateway/
    # need NET_ADMIN to run chaos linux experiments
    cap_add:
     - NET_ADMIN
    ports:
    - "8082:8082"
    networks:
    - servicenet
    volumes:
      - ./chaos-scripts:/var/chaosscripts
    depends_on:
      - docker-base-image

  toys:
    container_name: bestseller-toys
    build: bestseller-toys/
    # need NET_ADMIN to run chaos linux experiments
    cap_add:
      - NET_ADMIN
    ports:
    - "8081:8081"
    networks:
    - servicenet
    volumes:
      - ./chaos-scripts:/var/chaosscripts
    depends_on:
      - docker-base-image

  hot-deals:
    container_name: hot-deals
    build: hot-deals/
    image: mrbwilms/hot-deals
    # need NET_ADMIN to run chaos linux experiments
    cap_add:
      - NET_ADMIN
    ports:
    - "8083:8083"
    networks:
    - servicenet
    volumes:
      - ./chaos-scripts:/var/chaosscripts
    depends_on:
      - docker-base-image
