server:
  port: 8082

management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
chaos:
  monkey:
    enabled: false
    watcher:
      restController: true
      service: false
    assaults:
      latency-active: false
spring:
  profiles:
    active: chaos-monkey
  application:
    name: fashion-besteller